"""The round-8 notebook must stay in sync with the scripts it drives.

A notebook is the easiest artefact in the repository to break silently: it is
edited in a GUI, its diff is unreadable, and nothing compiles it. This one
launches multi-hour runs on the user's machine, so a mistyped flag or a stale
corpus name costs real time before anyone notices.

Two defences. The notebook is GENERATED by `scripts/make_round8_notebook.py`,
and these tests assert the checked-in file is exactly what that script
produces, so an in-Jupyter edit that was not regenerated fails CI. Everything
else here checks the properties that would waste a run.
"""
from __future__ import annotations

import ast
import json
import re
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
NB = ROOT / "notebooks" / "SignalShap_Round8_Runs.ipynb"
GEN = ROOT / "scripts" / "make_round8_notebook.py"

PAPER_CORPORA = ("ml_1m", "amazon_video_games", "gowalla_ts")
# The untimestamped LightGCN splits. Correct for the other notebook, wrong
# here: running them would produce artefacts for corpora the paper does not
# report, which is worse than producing none.
WRONG_CORPORA = ("yelp2018", "amazon_book_lgcn", "lastfm_2k", "amazon_book")


@pytest.fixture(scope="module")
def nb() -> dict:
    return json.loads(NB.read_text())


@pytest.fixture(scope="module")
def code_src(nb) -> str:
    return "\n".join("".join(c["source"])
                     for c in nb["cells"] if c["cell_type"] == "code")


def test_notebook_matches_its_generator():
    """Catch an edit made in Jupyter and committed without regenerating.

    The generator must NOT be allowed to overwrite the checked-in file before
    the comparison: an earlier version of this test did exactly that and could
    therefore never fail. Import the generator and build the notebook in
    memory instead, leaving the file on disk untouched.
    """
    import importlib.util

    spec = importlib.util.spec_from_file_location("_gen_r8", GEN)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)

    # Compare SOURCE only. A committed run legitimately carries outputs and
    # execution counts, and those must not be mistaken for drift; the thing
    # that must never diverge silently is the code being executed.
    def sources(nbdict):
        # Jupyter appends a trailing empty cell when a notebook is saved from
        # the UI. That is not drift, so empty cells are dropped before the
        # comparison.
        return [("".join(c["source"]), c["cell_type"]) for c in nbdict["cells"]
                if "".join(c["source"]).strip()]

    expected = sources(mod.build())
    actual = sources(json.loads(NB.read_text()))
    assert actual == expected, (
        "notebooks/SignalShap_Round8_Runs.ipynb differs from what "
        "scripts/make_round8_notebook.py produces. Edit the generator, then "
        "run `python scripts/make_round8_notebook.py`.")


def test_generation_is_deterministic():
    """Cell ids are content-hashed, so regeneration must be a no-op diff."""
    import importlib.util

    spec = importlib.util.spec_from_file_location("_gen_r8b", GEN)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    assert json.dumps(mod.build(), indent=1) == json.dumps(mod.build(), indent=1)


def test_every_code_cell_parses(nb):
    for i, c in enumerate(nb["cells"]):
        if c["cell_type"] != "code":
            continue
        src = "".join(c["source"])
        if src.lstrip().startswith("%"):      # magics are not python
            continue
        try:
            ast.parse(src)
        except SyntaxError as e:
            pytest.fail(f"cell {i} does not parse: {e}")


def test_notebook_is_valid_nbformat_with_ids(nb):
    assert nb["nbformat"] == 4 and nb["nbformat_minor"] >= 5
    ids = [c["id"] for c in nb["cells"]]
    assert all(ids), "every cell needs an id at nbformat 4.5+"
    assert len(set(ids)) == len(ids), "cell ids must be unique"


def test_only_the_papers_corpora_are_run(code_src):
    """The M4 notebook runs different corpora; this one must not."""
    for wrong in WRONG_CORPORA:
        assert wrong not in code_src, (
            f"{wrong!r} is not a corpus this paper reports; running it "
            f"produces artefacts for the wrong dataset")
    for right in PAPER_CORPORA:
        assert right in code_src, f"{right} is never run"


def test_every_script_invoked_exists(code_src):
    for script in set(re.findall(r'"(scripts/[\w./-]+\.py)"', code_src)):
        assert (ROOT / script).exists(), f"{script} does not exist"


def test_every_flag_is_defined_by_its_script(code_src):
    """A flag the target does not define aborts the stage instantly."""
    for call in re.findall(r'run\((.*?)\)\n', code_src, re.S):
        scripts = re.findall(r'"(scripts/[\w./-]+\.py)"', call)
        if not scripts:
            continue
        body = (ROOT / scripts[0]).read_text()
        for flag in re.findall(r'"(--[\w-]+)"', call):
            assert f'"{flag}"' in body, \
                f"{scripts[0]} does not define {flag}"


def test_run_study_is_called_with_one_corpus_at_a_time(code_src):
    """run_study.py refuses corpora needing different caps; respect that."""
    for call in re.findall(r'run\((.*?)\)\n', code_src, re.S):
        if "run_study.py" not in call:
            continue
        # The generated cell loops over CORPORA one at a time.
        assert "--datasets" in call
        assert "corpus" in call or call.count('"ml_1m"') <= 1, \
            "run_study.py must receive a single corpus per invocation"


def test_strict_data_is_enforced(code_src):
    """A missing corpus must be a hard error, never a synthetic fallback."""
    assert 'SIGNALSHAP_STRICT_DATA"] = "1"' in code_src


def test_the_runner_does_not_abort_the_remaining_stages(code_src):
    """One failed stage must not discard the hours of work after it."""
    assert "allow_fail=True" in code_src
    assert "RESULTS[label]" in code_src, "stage outcomes must be recorded"


def test_blocked_retirement_actually_requests_retirement(code_src):
    """Without the flag this stage silently reproduces the old split-only run."""
    assert "--retirement" in code_src


def test_ten_seeds_are_requested_for_the_protocol_contrast(code_src):
    """Item 7 is specifically about replacing the single-seed run."""
    assert "range(42, 52)" in code_src or len(
        re.findall(r'"4[2-9]"|"5[01]"', code_src)) >= 10


def test_reporting_cells_tolerate_a_missing_artefact(code_src):
    """Reading a not-yet-written artefact must report, not traceback.

    Found by executing the notebook: `show_pools` called `read_artefact`,
    which raises FileNotFoundError before the stage has ever run, so the
    summary cell died on a perfectly normal state.
    """
    block = code_src[code_src.index("def show_pools"):]
    block = block[:block.index("\n\n\n")] if "\n\n\n" in block else block
    assert "exists()" in block, \
        "show_pools must check for the artefact before reading it"


def test_empty_summary_does_not_claim_success(code_src):
    """An empty results table means nothing ran, not that everything passed."""
    assert "NO STAGES RAN" in code_src


def test_notebook_warns_against_the_other_notebook(nb):
    """The likeliest expensive mistake is running the M4 notebook instead."""
    md = "\n".join("".join(c["source"])
                   for c in nb["cells"] if c["cell_type"] == "markdown")
    assert "SignalShap_M4_FullStudy" in md
    assert "not" in md.lower()


def test_repo_is_located_by_contents_not_by_a_guessed_path(code_src, tmp_path):
    """A stale empty ~/signalshap-code must not be mistaken for the repo.

    This is a regression test for a real failure. The first version of the
    notebook did `REPO = Path.home()/"signalshap-code"` guarded only by
    `.exists()`. The user had an empty directory at exactly that path while
    the real clone lived under Desktop/..., so the assert passed, the notebook
    chdir'd into the empty directory, and all nine stages died instantly with
    "can't open file scripts/run_study.py". Nothing ran and nothing warned.
    """
    assert "_find_repo" in code_src, "repo must be discovered, not hardcoded"
    assert "MARKERS" in code_src, "discovery must probe for known files"

    # Execute the setup cell with HOME pointing at a decoy empty directory.
    decoy = tmp_path / "home"
    (decoy / "signalshap-code").mkdir(parents=True)

    cell = next("".join(c["source"]) for c in json.loads(NB.read_text())["cells"]
                if c["cell_type"] == "code" and "_find_repo" in "".join(c["source"]))
    prog = (
        "import os, sys\n"
        f"os.environ['HOME'] = {str(decoy)!r}\n"
        f"os.chdir({str(ROOT)!r})\n"
        + cell
        + "\nprint('RESOLVED', REPO)\n")
    r = subprocess.run([sys.executable, "-c", prog], capture_output=True,
                       text=True, cwd=ROOT)
    assert r.returncode == 0, r.stderr[-2000:]
    assert f"RESOLVED {ROOT}" in r.stdout, (
        f"resolved the wrong directory:\n{r.stdout}\n{r.stderr[-800:]}")


def test_missing_repo_fails_loudly_rather_than_running_nothing(tmp_path):
    """If discovery fails it must raise with instructions, not chdir anyway."""
    cell = next("".join(c["source"]) for c in json.loads(NB.read_text())["cells"]
                if c["cell_type"] == "code" and "_find_repo" in "".join(c["source"]))
    empty = tmp_path / "nowhere"
    empty.mkdir()
    prog = (
        "import os, sys\n"
        f"os.environ['HOME'] = {str(tmp_path)!r}\n"
        f"os.chdir({str(empty)!r})\n"
        + cell)
    r = subprocess.run([sys.executable, "-c", prog], capture_output=True,
                       text=True, cwd=empty)
    assert r.returncode != 0, "must not proceed when the repo is not found"
    assert "Could not locate" in (r.stdout + r.stderr)


def test_kernel_interpreter_mismatch_is_surfaced(code_src):
    """Stages shell out with sys.executable; a wrong kernel changes the env."""
    assert ".venv" in code_src and "WARNING: kernel is" in code_src
